persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
    config.reload.automatic: true

logstashPipeline:
  uptime.conf: |
    output {
      stdout {
        codec => rubydebug   
      }
      elasticsearch {
        hosts => ["https://elasticsearch-master:9200"]
        user => '${ELASTICSEARCH_USERNAME}'
        cacert => '/usr/share/logstash/config/certs/ca.crt'
        password => '${ELASTICSEARCH_PASSWORD}'
        index => "logstash-%{+YYYY.MM.dd.HH}"
      }
    }

extraEnvs:
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password

secretMounts: 
  - name: elasticsearch-master-certs
    secretName: elasticsearch-master-certs
    path: /usr/share/logstash/config/certs
service:
  name: logstash
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
  selector:
    app: logstash-logstash

